import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { createClient } from '@/utils/supabase/server';
import { Toaster } from 'sonner'
import ToastWatcher from "@/components/ToastWatcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Kullanıcıyı layout'ta çekiyoruz
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  return (
    <html lang="tr">
      <body className="antialiased bg-black text-white selection:bg-red-600 selection:text-white">
        {/* Navbar'a user bilgisini gönderiyoruz */}
        <Navbar user={user} />
          {children}
        {/* --- BİLDİRİM SİSTEMİ --- */}
        <ToastWatcher /> {/* URL'yi izleyen ajan */}
        <Toaster 
          position="bottom-right" 
          theme="dark"
          toastOptions={{
            style: {
              background: '#0a0a0a',
              border: '1px solid #333',
              color: 'white',
            },
            className: 'font-sans'
          }}
        />

      </body>
    </html>
  );
}